# =============================================================================
#  Spark Data Lake - control shortcuts
#  Just type "make" to see every available command.
# =============================================================================

# Load .env if it exists (the "-" avoids an error when the file is missing).
-include .env
export

COMPOSE := docker compose
APP     := $(COMPOSE) exec -T spark-app

.DEFAULT_GOAL := help
.PHONY: help setup build up down restart ps logs logs-master logs-worker \
		shell smoke check-db psql ui clean reset-data \
		generate bronze silver gold gold-sql warehouse pipeline quality \
		demo-basics demo-partitions demo-lazy demo-parquet demo-joins demo-cache demos \
		test bench notebook

# Number of orders generated by "make generate" (overridable):
#     make generate ROWS=5000000
ROWS ?= 1000000

help: ## Show this help
	@echo ""
	@echo "  Spark Data Lake - available commands"
	@echo "  ------------------------------------"
	@awk 'BEGIN {FS = ":.*## "} /^[a-zA-Z_-]+:.*## / \
		{printf "  \033[36m%-16s\033[0m %s\n", $$1, $$2}' $(MAKEFILE_LIST)
	@echo ""

setup: ## Create .env from .env.example (never overwrites it)
	@if [ -f .env ]; then \
		echo "  .env already exists: nothing to do."; \
	else \
		cp .env.example .env; \
		echo "  .env created. Change POSTGRES_PASSWORD before going further."; \
	fi

build: ## Build the project Docker image
	$(COMPOSE) build

up: ## Start the cluster (master + worker + app + postgres)
	$(COMPOSE) up -d
	@echo ""
	@echo "  Spark Master UI : http://localhost:$(SPARK_MASTER_UI_PORT)"
	@echo "  Spark Worker UI : http://localhost:$(SPARK_WORKER_UI_PORT)"
	@echo "  Spark App UI    : http://localhost:$(SPARK_APP_UI_PORT)  (while a job runs)"
	@echo "  PostgreSQL      : localhost:$(POSTGRES_HOST_PORT)"
	@echo ""

down: ## Stop the containers (the PostgreSQL data is kept)
	$(COMPOSE) down

restart: down up ## Restart the cluster

ps: ## Container status
	$(COMPOSE) ps

logs: ## Logs of every service (Ctrl+C to exit)
	$(COMPOSE) logs -f --tail=50

logs-master: ## Logs of the Spark Master
	$(COMPOSE) logs -f --tail=80 spark-master

logs-worker: ## Logs of the Spark Worker
	$(COMPOSE) logs -f --tail=80 spark-worker

shell: ## Open a terminal inside the application container
	$(COMPOSE) exec spark-app bash

smoke: ## Check end to end that the Spark cluster works
	$(APP) spark-submit /opt/workspace/scripts/smoke_test.py

check-db: ## Check that PostgreSQL answers from the application container
	$(APP) python3 /opt/workspace/scripts/check_postgres.py

psql: ## Open a SQL console on the data warehouse
	$(COMPOSE) exec postgres psql -U $(POSTGRES_USER) -d $(POSTGRES_DB)

ui: ## Open the Spark web interfaces in the browser
	@xdg-open http://localhost:$(SPARK_MASTER_UI_PORT) >/dev/null 2>&1 || \
		echo "  Open it manually: http://localhost:$(SPARK_MASTER_UI_PORT)"

# =============================================================================
#  PIPELINE
# =============================================================================

generate: ## Generate the source dataset (ROWS=1000000 by default)
	$(APP) python3 -m src.generator.generate_data --rows $(ROWS) --clean

bronze: ## RAW -> BRONZE (raw ingestion into Parquet)
	$(APP) spark-submit src/spark/ingest_bronze.py

silver: ## BRONZE -> SILVER (cleaning, validation, deduplication)
	$(APP) spark-submit src/spark/bronze_to_silver.py

gold: ## SILVER -> GOLD (analytical aggregates)
	$(APP) spark-submit src/spark/silver_to_gold.py

gold-sql: ## SILVER -> GOLD through Spark SQL (same results)
	$(APP) spark-submit src/spark/silver_to_gold.py --engine sql

warehouse: ## GOLD -> PostgreSQL
	$(APP) spark-submit src/warehouse/load_postgres.py

pipeline: generate bronze silver gold warehouse ## Run the whole pipeline
	@echo ""
	@echo "  Full pipeline: RAW -> BRONZE -> SILVER -> GOLD -> PostgreSQL"
	@echo ""

quality: ## Print the data quality reports
	@for f in data/quality/*.json; do echo "--- $$f"; cat $$f; echo; done

# =============================================================================
#  TEACHING DEMOS
# =============================================================================

demo-basics: ## DataFrame API: select, filter, join, groupBy...
	$(APP) spark-submit src/spark/demos/01_dataframe_basics.py

demo-partitions: ## Partitions, repartition vs coalesce, data skew
	$(APP) spark-submit src/spark/demos/02_partitions.py

demo-lazy: ## Lazy evaluation, transformations vs actions, DAG, shuffle
	$(APP) spark-submit src/spark/demos/03_lazy_shuffle.py

demo-parquet: ## CSV vs Parquet, predicate pushdown, partition pruning
	$(APP) spark-submit src/spark/demos/04_parquet_vs_csv.py

demo-joins: ## Inner/left/anti join, sort merge vs broadcast
	$(APP) spark-submit src/spark/demos/05_joins_broadcast.py

demo-cache: ## cache(), persist(), and why not to overuse them
	$(APP) spark-submit src/spark/demos/06_cache_performance.py

demos: demo-basics demo-partitions demo-lazy demo-parquet demo-joins demo-cache ## Every demo

# =============================================================================
#  QUALITY
# =============================================================================

notebook: ## Start JupyterLab (the URL with the token appears in the output)
	$(COMPOSE) exec spark-app jupyter lab --ip=0.0.0.0 --port=8888 \
		--no-browser --notebook-dir=/opt/workspace

test: ## Run the pytest suite (in the container, Spark in local[2])
	$(APP) python3 -m pytest tests/ -v

bench: ## Benchmark Pandas vs PySpark (SIZES="10mb 100mb")
	$(APP) python3 -m benchmarks.pandas_vs_spark --sizes $(or $(SIZES),10mb 100mb)

reset-data: ## Empty data/bronze, data/silver and data/gold (keeps data/raw)
	@echo "  Deleting the contents of data/bronze, data/silver, data/gold..."
	@rm -rf data/bronze/* data/silver/* data/gold/*
	@touch data/bronze/.gitkeep data/silver/.gitkeep data/gold/.gitkeep
	@echo "  Done."

clean: ## Remove containers AND the PostgreSQL volume (destructive, asks first)
	@printf "  This will delete the PostgreSQL database. Continue? [y/N] " && read ans && [ "$$ans" = "y" ]
	$(COMPOSE) down -v
